routes/api_customers.py
from flask import Blueprint, jsonify, request, redirect, url_for
from db import db
from models import Customer

# Create a Blueprint for the customers API
api_customers_bp = Blueprint("api_customers", __name__)

@api_customers_bp.route("/", methods=["GET"])
def get_customers():
    statement = db.select(Customer).order_by(Customer.name)
    records = db.session.execute(statement)
    results = records.scalars()
    return jsonify([cust.to_json() for cust in results])

@api_customers_bp.route("/<int:id>", methods=["PUT"])
def update_balance(id):
    data = request.get_json()
    customer = db.get_or_404(Customer, id)
    if "balance" not in data:
        return "Invalid Request", 405
    balance = data["balance"]
    if not isinstance(balance, (int, float)):
        return "Invalid Request", 405
    customer.balance = balance
    db.session.commit()
    return "", 204

@api_customers_bp.route("/<int:id>", methods=["DELETE"])
def delete_customer(id):
    customer = db.get_or_404(Customer, id)
    db.session.delete(customer)
    db.session.commit()
    return "", 204

@api_customers_bp.route("/<int:id>", methods=["POST"])
def delete_customer_post(id):
    customer = db.get_or_404(Customer, id)
    db.session.delete(customer)
    db.session.commit()
    return redirect(url_for("html.customers_info"))

@api_customers_bp.route("/", methods=["POST"])
def customers_json():
    # ! This method uses the form in my html so not as per the project instructions
    if request.form:
        data = request.form.to_dict()
        customer = Customer(**data)
        db.session.add(customer)
        db.session.commit()
    else:
        data = request.get_json()
        if "name" not in data or "balance" not in data or "phone" not in data:
            return "Invalid Request", 400
        name = data["name"]
        if not isinstance(name, str):
            return "Invalid Request", 400
        balance = data["balance"]
        if not isinstance(balance, (int, float)) or balance < 0:
            return "Invalid Request", 400
        phone = data["phone"]
        db.session.add(Customer(name=name, balance=balance, phone=phone))
        db.session.commit()
    return redirect(url_for("html.customers_info"))

routes/api_orders_bp.py
from flask import Blueprint, jsonify, request, redirect, url_for, render_template
from db import db
from models import Customer, Products, Order, ProductOrder

# Create a Blueprint for the customers API
api_order_bp = Blueprint("api_orders", __name__)

@api_order_bp.route("", methods=["POST"])
def add_order():
    data = request.get_json()
    if "customer_id" not in data:
        return "Invalid Request", 400
    customer_id = data["customer_id"]
    customer = db.get_or_404(Customer, customer_id)
    order = Order(customer=customer)
    db.session.add(order)
    for i in data["items"]:
        product_name = i["name"]
        statement = db.select(Products).where(Products.name == product_name)
        product = db.session.execute(statement).scalar()
        if product is None:
            # skip this product
            continue
        product = db.get_or_404(Products, product.id)

        quantity = i["quantity"]
        product_order = ProductOrder(order=order, product=product, quantity=quantity)
        db.session.add(product_order)
    db.session.commit()
    return "", 201

@api_order_bp.route("/<int:id>/delete", methods=["POST"])
def delete_order(id):
    order = db.get_or_404(Order, id)
    if order.processed is not None:
        return redirect(url_for("html.orders"))
    db.session.delete(order)
    db.session.commit()
    return redirect(url_for("html.orders"))

@api_order_bp.route("/<int:id>", methods=["DELETE"])
def delete_order_api(id):
    order = db.get_or_404(Order, id)
    if order.processed is not None:
        return "Invalid Request", 405
    db.session.delete(order)
    db.session.commit()
    return "", 204  

@api_order_bp.route("/<int:id>", methods=["PUT", "POST"])
def process_order(id):
    if request.form:
        data = request.form.to_dict()
    else:
        data = request.get_json()
    order = db.get_or_404(Order, id)

    if order.processed is not None:
        return redirect(url_for("html.orders"))
    if "process" in data:
        if data["process"] == "True":
            process = True
        else:
            process = False
            return redirect(url_for("html.orders"))
        
    process = True

    if process:
        if "strategy" not in data:
            strategy = "adjust"
        else:
            strategy = data["strategy"]
        if strategy not in ["adjust", "reject", "ignore"]:
            return "Invalid Request", 403
        if  not order.process(strategy):
            return redirect(url_for("html.orders"))
        
    return redirect(url_for("html.orders"))

routes/html_bp.py
from flask import Blueprint, jsonify, request, redirect, url_for, render_template
from db import db
from models import Customer, Products, Order, ProductOrder

# Create a Blueprint for the customers API
htmls_bp = Blueprint("html", __name__)

@htmls_bp.route("/")
def home():
    return render_template(
        "home.html", name="Ashutosh Dhatwalia"
    )

@htmls_bp.route("/customers")
def customers_info():
    statement = db.select(Customer)
    records = db.session.execute(statement)
    results = records.scalars()
    return render_template("customers.html", customers=results)

@htmls_bp.route("/customers/<int:id>", methods=["GET"])
def customer_info(id):
    customer = db.get_or_404(Customer, id)
    return render_template("customer.html", customer=customer)

@htmls_bp.route("/products")
def products_info():
    statement = db.select(Products)
    records = db.session.execute(statement)
    results = records.scalars()
    return render_template("products.html", products=results)

@htmls_bp.route("/orders", methods=["GET"])
def orders():
    statement = db.select(Order)
    records = db.session.execute(statement)
    results = records.scalars()
    return render_template("orders.html", orders=results)

@htmls_bp.route("/orders/<int:id>", methods=["GET"])
def orders_info(id):
    order = db.get_or_404(Order, id)
    return render_template("order.html", order=order)

templates/base.html
<!doctype html>
<html lang="en">

    <head>
        <title>Flask App</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    </head>
    <body>
        <nav class="d-flex justify-content-around">
            <a class="btn btn-primary" href='{{url_for("html.home")}}'>Home</a>
            <a class="btn btn-primary" href='{{url_for("html.customers_info")}}'>Customers</a>
            <a class="btn btn-primary" href='{{url_for("html.products_info")}}'>Products</a>
            <a class="btn btn-primary" href='{{url_for("html.orders")}}'>Orders</a>
        </nav>
        {% block content %}
        {% endblock %}
        
    </body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </html>

templates/customer.html
{% extends "base.html" %} {% block content %}
<h1>Customer Info</h1>
<br />
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Customer ID</th>
      <th scope="col">Name</th>
      <th scope="col">Phone</th>
      <th scope="col">Balance</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">{{customer.id}}</th>
      <td>{{customer.name}}</td>
      <td>{{customer.phone}}</td>
      <td>{{customer.balance}}</td>
    </tr>
  </tbody>
</table>
<a class="btn btn-primary" href="{{url_for('html.customers_info')}}">Back</a>
{% for order in customer.orders %}
<p>Order: {{order.id}}</p>
<a class="btn btn-primary" href="{{url_for('html.orders_info', id=order.id)}}"
  >Orders</a
>
{%endfor%} {% endblock %}

templates/customers.html
{% extends "base.html" %} {% block content %}
<h1 class="d-flex justify-content-center">Customers</h1>
<div class="d-flex justify-content-center">
  <button
    type="button"
    class="btn btn-primary"
    data-bs-toggle="modal"
    data-bs-target="#exampleModalCenter"
  >
    Add Customer
  </button>
</div>
<!-- Modal -->
<div
  class="modal fade"
  id="exampleModalCenter"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalCenterTitle"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Add Customer</h5>
      </div>
      <div class="modal-body">
        <form
          method="post"
          action='{{url_for("api_customers.customers_json")}}'
        >
          <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" name="name" />
          </div>
          <div class="mb-3">
            <label for="phone" class="form-label">Phone</label>
            <input type="text" class="form-control" id="phone" name="phone" />
          </div>
          <div class="mb-3">
            <label for="balance" class="form-label">Balance</label>
            <input
              type="text"
              class="form-control"
              id="balance"
              name="balance"
            />
          </div>
          <button
            type="button"
            class="btn btn-secondary"
            data-bs-dismiss="modal"
          >
            Close
          </button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </form>
      </div>
    </div>
  </div>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Customer ID</th>
      <th scope="col">Customer Name</th>
      <th scope="col">Customer Phone</th>
      <th scope="col">Customer Balance</th>
      <th scope="col">Customer Details</th>
      <th scope="col">Delete Customer</th>
    </tr>
  </thead>
  <tbody>
    {% for customer in customers %}
    <tr>
      <th scope="row">{{ customer.id }}</th>
      <td>{{ customer.name }}</td>
      <td>{{ customer.phone }}</td>
      {% if customer.balance < 0 %}
      <td class="text-danger">{{ customer.balance }}</td>
      {% else %}
      <td class="text-success">{{ customer.balance }}</td>
      {% endif %}
      <td>
        <a href='{{url_for("html.customer_info", id=customer.id)}}'>Details</a>
      </td>
      <td>
        <form
          method="POST"
          action='{{url_for("api_customers.delete_customer_post", id=customer.id)}}'
        >
          <button type="submit" class="btn btn-primary">Delete</button>
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<!-- Button trigger modal -->
{% endblock %}

templates/home.html
{%extends "base.html"%} {%block content%} <br />
<h1 class="d-flex justify-content-center align-items-center">
  Hi there, welcome to my e-shop! My name is {{name}}
</h1>
{%endblock%}

templates/order.html
{%extends "base.html"%} {%block content%}

<h1 class="d-flex justify-content-center">Order Info</h1>
<br />

<table class="table table-hover">
<thead>
  <tr>
    <th scope="col">Order ID</th>
    <th scope="col">Customer ID</th>
    <th scope="col">Total Costs</th>
  </tr>
</thead>
<tbody>
<tbody>
  <tr>
  <th scope="row">Order ID: {{order.id}}</th>
  <td>Customer ID: {{order.customer_id}}</td>
  <td>Total: {{order.total()}}</td>
</tr>
</tbody>
</table>
  <h3 class="d-flex justify-content-center">Products</h3>
  <br />
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Item Name</th>
        <th scope="col">Product Quantity</th>
        <th scope="col">Per Unit Price</th>
        <th scope="col">Product Stock</th>
      </tr>
    </thead>
    <tbody>
      {% for item in order.items %}
      <tr>
        <th scope="row">{{item.product.name}}</th>
        {% if item.quantity > item.product.available %}
        <td class="text-danger">{{item.quantity}}</td>
        {% else %}
        <td class="text-success">{{item.quantity}}</td>
        {% endif %}
        <td>{{item.product.price}}</td>
        <td>{{item.product.available}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="d-flex justify-content-around">
  <form
    method="POST"
    action="{{url_for('api_orders.process_order', id=order.id)}}"
  >
    <button
      type="submit"
      class="btn btn-primary"
      name="strategy"
      value="adjust"
    >
      Process with adjust
    </button>
  </form>
  <form
    method="POST"
    action="{{url_for('api_orders.process_order', id=order.id)}}"
  >
    <button
      type="submit"
      class="btn btn-primary"
      value="reject"
      name="strategy"
    >
      Process with reject
    </button>
  </form>
  <form
    method="POST"
    action="{{url_for('api_orders.process_order', id=order.id)}}"
  >
    <button
      type="submit"
      class="btn btn-primary"
      name="strategy"
      value="ignore"
    >
      Process with ignore
    </button>
  </form>
  {%endblock%}
</div>

templates/orders.html
{% extends "base.html" %} {% block content %}
<h1>Orders</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Order ID</th>
      <th scope="col">Customer Name</th>
      <th scope="col">Total</th>
      <th scope="col">Created at</th>
      <th scope="col">Order Condition</th>
    </tr>
  </thead>
  <tbody>
    {% for order in orders %}
    <tr>
      <th scope="row">{{order.id}}</th>
      <td>{{order.customer.name}}</td>
      <td>${{order.total()}}</td>
      <td>{{order.created_at}}</td>
      <td>
        {% if order.processed %}
        <p class="text-success">Confirmed</p>
        {% else %}
        <p class="text-danger">Not processed</p>
        {% endif %}
      </td>
      <td>
        <a href="{{url_for('html.orders_info', id=order.id)}}">Details</a>
      </td>
      <td>
        <form
          method="POST"
          action="{{ url_for('api_orders.delete_order', id=order.id) }}"
        >
          <button type="submit" class="btn btn-primary">Delete</button>
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/products.html
{% extends "base.html" %} {% block content %}
<h1>Products</h1>
<br />
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Product ID</th>
      <th scope="col">Product Name</th>
      <th scope="col">Price per Unit</th>
      <th scope="col">Product Stock</th>
    </tr>
  </thead>
  <tbody>
    {% for product in products %}
    <tr>
      <th scope="row">{{ product.id }}</th>
      <td>{{ product.name }}</td>
      <td>{{ product.price }}</td>
      <td>{{ product.available }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}